{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyP7JB7NupBabPnUC3JDxNDL",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/pinpan123/Automata/blob/main/app.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "ttvdAMQYYfOc"
      },
      "outputs": [],
      "source": [
        "import streamlit as st\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import pydeck as pdk\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "import plotly.express as px\n",
        "import plotly.graph_objects as go\n",
        "import joblib\n",
        "st.set_option('deprecation.showPyplotGlobalUse', False)\n",
        "DATA_URL = (\"Autodata.csv\")\n",
        "\n",
        "st.title('AUTOMATA - Data Analysis platform for the Automotive Industry ')\n",
        "st.image('car1.png')\n",
        "\n",
        "st.write('')\n",
        "\n",
        "cars = pd.read_csv('Autodata.csv')\n",
        "cars.head()\n",
        "\n",
        "#-----------------------------------------------------------------------------------------------\n",
        "# DATA INSPECTION --------------------------------------------------------------------------------\n",
        "\n",
        "cars.shape\n",
        "\n",
        "cars.describe()\n",
        "\n",
        "cars.info()\n",
        "\n",
        "#-----------------------------------------------------------------------------------------------\n",
        "# DATA CLEANING --------------------------------------------------------------------------------\n",
        "\n",
        "#Splitting company name from CarName column\n",
        "CompanyName = cars['CarName'].apply(lambda x : x.split(' ')[0])\n",
        "cars.insert(3,\"CompanyName\",CompanyName)\n",
        "cars.drop(['CarName'],axis=1,inplace=True)\n",
        "cars.head()\n",
        "\n",
        "\n",
        "# cars.CompanyName.unique()\n",
        "\n",
        "cars.CompanyName = cars.CompanyName.str.lower()\n",
        "\n",
        "def replace_name(a,b):\n",
        "    cars.CompanyName.replace(a,b,inplace=True)\n",
        "\n",
        "replace_name('maxda','mazda')\n",
        "replace_name('porcshce','porsche')\n",
        "replace_name('toyouta','toyota')\n",
        "replace_name('vokswagen','volkswagen')\n",
        "replace_name('vw','volkswagen')\n",
        "\n",
        "cars.CompanyName.unique()\n",
        "\n",
        "#Checking for duplicates\n",
        "cars.loc[cars.duplicated()]\n",
        "\n",
        "cars.columns\n",
        "\n",
        "# ---------------------------------------------------------------------------------------------------\n",
        "# 2. EXPLORATORY DATA ANALYSIS---------------------------------------------------------------------\n",
        "\n",
        "st.header('Price')\n",
        "st.text('Price distribution plot and Price spread')\n",
        "fig1 = plt.figure(figsize=(16,8))\n",
        "\n",
        "plt.subplot(1,2,1)\n",
        "plt.title('Car Price Distribution Plot')\n",
        "sns.distplot(cars.price)\n",
        "\n",
        "plt.subplot(1,2,2)\n",
        "plt.title('Car Price Spread')\n",
        "sns.boxplot(y=cars.price)\n",
        "\n",
        "plt.show()\n",
        "\n",
        "st.write(fig1)\n",
        "\n",
        "st.text('Inference :')\n",
        "\n",
        "st.text('1. The plot seemed to be right-skewed, meaning that the most prices in the dataset')\n",
        "st.text('are low(Below 15,000).')\n",
        "st.text('2. There is a significant difference between the mean and the median of the price')\n",
        "st.text(' distribution.')\n",
        "st.text('3. The data points are far spread out from the mean, which indicates a high variance ')\n",
        "st.text(' in the car prices.(85% of the prices are below 18,500, whereas the remaining')\n",
        "st.text('15% are between 18,500 and 45,400.)')\n",
        "st.write('')\n",
        "st.write('')\n",
        "st.write('')\n",
        "\n",
        "st.header('Categorical Data')\n",
        "\n",
        "st.text('- CompanyName')\n",
        "st.text('- Symboling')\n",
        "st.text('- fueltype')\n",
        "st.text('- enginetype')\n",
        "st.text('- carbody')\n",
        "st.text('- doornumber')\n",
        "st.text('- enginelocation')\n",
        "st.text('- fuelsystem')\n",
        "st.text('- cylindernumber')\n",
        "st.text('- aspiration')\n",
        "st.text('- drivewheel')\n",
        "\n",
        "\n",
        "\n",
        "print(cars.price.describe(percentiles = [0.25,0.50,0.75,0.85,0.90,1]))\n",
        "st.header('Most Favourable')\n",
        "fig2 = plt.figure(figsize=(16, 8))\n",
        "\n",
        "plt.subplot(1,3,1)\n",
        "plt1 = cars.CompanyName.value_counts().plot(kind='bar')\n",
        "plt.title('Most Favourable Company')\n",
        "plt1.set(xlabel = 'Car company', ylabel='Frequency of company')\n",
        "\n",
        "plt.subplot(1,3,2)\n",
        "plt1 = cars.fueltype.value_counts().plot(kind='bar')\n",
        "plt.title('Most Favourable Fuel Type')\n",
        "plt1.set(xlabel = 'Fuel Type', ylabel='Frequency of fuel type')\n",
        "\n",
        "plt.subplot(1,3,3)\n",
        "plt1 = cars.carbody.value_counts().plot(kind='bar')\n",
        "plt.title('Most Favourable Car Type')\n",
        "plt1.set(xlabel = 'Car Type', ylabel='Frequency of Car type')\n",
        "\n",
        "plt.show()\n",
        "st.write(fig2)\n",
        "\n",
        "st.text('Inference :')\n",
        "\n",
        "st.text('1. Toyota seemed to be the most popular car brand.')\n",
        "st.text('2. Number of gas fueled cars are more than diesel.')\n",
        "st.text('3. Sedan is the top car type preferred.')\n",
        "st.write('')\n",
        "st.write('')\n",
        "st.write('')\n",
        "\n",
        "st.header('Symbolling')\n",
        "st.text(\"Symbolling value shows how risky or safe a vehicle is, from an insurer's perspective.\")\n",
        "st.text('It can range from -3 to +3.')\n",
        "st.text('-3 indicates a safe car while +3 denotes a risky one.')\n",
        "fig3 = plt.figure(figsize=(20,8))\n",
        "\n",
        "plt.subplot(1,2,1)\n",
        "plt.title('Symboling Histogram')\n",
        "sns.countplot(cars.symboling, palette=(\"cubehelix\"))\n",
        "\n",
        "plt.subplot(1,2,2)\n",
        "plt.title('Symboling vs Price')\n",
        "sns.boxplot(x=cars.symboling, y=cars.price, palette=(\"cubehelix\"))\n",
        "\n",
        "plt.show()\n",
        "st.write(fig3)\n",
        "\n",
        "st.text('Inference :')\n",
        "\n",
        "st.text('1. It seems that the symboling with 0 and 1 values have high number of rows')\n",
        "st.text('(i.e. They are most sold.)')\n",
        "st.text('2. The cars with -1 symboling seems to be high priced (as it makes sense too,')\n",
        "st.text('insurance risk rating -1 is quite good). But it seems that symboling with 3 value')\n",
        "st.text(' has the price range similar to -2 value.There is a dip in price at symboling 1')\n",
        "st.write('')\n",
        "st.write('')\n",
        "st.write('')\n",
        "\n",
        "\n",
        "st.header('Engine')\n",
        "st.text('Let us look on the most favourable engine type and compare the price.')\n",
        "fig4 = plt.figure(figsize=(18,6))\n",
        "\n",
        "plt.subplot(1,2,1)\n",
        "plt.title('Engine Type Histogram')\n",
        "sns.countplot(cars.enginetype, palette=(\"Blues_d\"))\n",
        "\n",
        "plt.subplot(1,2,2)\n",
        "plt.title('Engine Type vs Price')\n",
        "sns.boxplot(x=cars.enginetype, y=cars.price, palette=(\"PuBuGn\"))\n",
        "plt.show()\n",
        "st.write(fig4)\n",
        "# st.write(fig4)\n",
        "\n",
        "df = pd.DataFrame(cars.groupby(['enginetype'])['price'].mean().sort_values(ascending = False))\n",
        "df.plot.bar(figsize=(18,6))\n",
        "plt.title('Engine Type vs Average Price')\n",
        "st.pyplot()\n",
        "\n",
        "st.text('Inference :')\n",
        "\n",
        "st.text('1. ohc Engine type seems to be most favored type.')\n",
        "st.text('2. ohcv has the highest price range (While dohcv has only one row),')\n",
        "st.text('ohc and ohcf have the low price range.')\n",
        "st.write('')\n",
        "st.write('')\n",
        "st.write('')\n",
        "\n",
        "st.header('Average Price')\n",
        "fig5 = plt.figure(figsize=(18,6))\n",
        "\n",
        "df = pd.DataFrame(cars.groupby(['CompanyName'])['price'].mean().sort_values(ascending = False))\n",
        "df.plot.bar(figsize=(18,6))\n",
        "plt.title('Company Name vs Average Price')\n",
        "plt.show()\n",
        "st.pyplot()\n",
        "\n",
        "df = pd.DataFrame(cars.groupby(['fueltype'])['price'].mean().sort_values(ascending = False))\n",
        "df.plot.bar(figsize=(18,6))\n",
        "plt.title('Fuel Type vs Average Price')\n",
        "plt.show()\n",
        "st.pyplot()\n",
        "\n",
        "df = pd.DataFrame(cars.groupby(['carbody'])['price'].mean().sort_values(ascending = False))\n",
        "df.plot.bar(figsize=(18,6))\n",
        "plt.title('Car Type vs Average Price')\n",
        "plt.show()\n",
        "st.pyplot()\n",
        "\n",
        "# st.write(fig5)\n",
        "st.text('Inference :')\n",
        "\n",
        "st.text('1. Jaguar and Buick seem to have highest average price.')\n",
        "st.text('2. Diesel has higher average price than  gas.')\n",
        "st.text('3. Hardtop and convertible have higher average price.')\n",
        "st.write('')\n",
        "st.write('')\n",
        "st.write('')\n",
        "\n",
        "st.header('Doors')\n",
        "fig6 = plt.figure(figsize=(15,5))\n",
        "\n",
        "plt.subplot(1,2,1)\n",
        "plt.title('Door Number Histogram')\n",
        "sns.countplot(cars.doornumber, palette=(\"plasma\"))\n",
        "\n",
        "plt.subplot(1,2,2)\n",
        "plt.title('Door Number vs Price')\n",
        "sns.boxplot(x=cars.doornumber, y=cars.price, palette=(\"plasma\"))\n",
        "\n",
        "plt.show()\n",
        "st.write(fig6)\n",
        "st.text('Inference :')\n",
        "st.text('1. Mostly people prefer 4 door wheelers.')\n",
        "st.text('2. Doornumber variable is not affacting the price much. There is no sugnificant')\n",
        "st.text('difference between the categories in it.')\n",
        "st.write('')\n",
        "st.write('')\n",
        "st.write('')\n",
        "\n",
        "st.header('Aspiration')\n",
        "fig7 = plt.figure(figsize=(15,5))\n",
        "\n",
        "plt.subplot(1,2,1)\n",
        "plt.title('Aspiration Histogram')\n",
        "sns.countplot(cars.aspiration, palette=(\"plasma\"))\n",
        "\n",
        "plt.subplot(1,2,2)\n",
        "plt.title('Aspiration vs Price')\n",
        "sns.boxplot(x=cars.aspiration, y=cars.price, palette=(\"plasma\"))\n",
        "\n",
        "plt.show()\n",
        "st.write(fig7)\n",
        "st.text('It seems aspiration with turbo have higher price range than the std (though it')\n",
        "st.text('has some high values outside the whiskers.)')\n",
        "st.write('')\n",
        "st.write('')\n",
        "st.write('')\n",
        "\n",
        "st.header('Engine Location, Cylinder Number, Fuel System, Drive Wheel')\n",
        "def plot_count(x,fig):\n",
        "    plt.subplot(4,2,fig)\n",
        "    plt.title(x+' Histogram')\n",
        "    sns.countplot(cars[x],palette=(\"magma\"))\n",
        "    plt.subplot(4,2,(fig+1))\n",
        "    plt.title(x+' vs Price')\n",
        "    sns.boxplot(x=cars[x], y=cars.price, palette=(\"magma\"))\n",
        "    \n",
        "fig8 = plt.figure(figsize=(15,20))\n",
        "\n",
        "plot_count('enginelocation', 1)\n",
        "plot_count('cylindernumber', 3)\n",
        "plot_count('fuelsystem', 5)\n",
        "plot_count('drivewheel', 7)\n",
        "\n",
        "plt.tight_layout()\n",
        "st.write(fig8)\n",
        "\n",
        "st.text('Inference :')\n",
        "\n",
        "st.text('1. Very few datapoints for enginelocation categories to make an inference.')\n",
        "st.text('2. Most common number of cylinders are four, six and five. Though eight')\n",
        "st.text('cylinders have the highest price range.')\n",
        "st.text('3. mpfi and 2bbl are most common type of fuel systems. mpfi and idi having')\n",
        "st.text('the highest price range. But there are few data for other categories to derive any')\n",
        "st.text('meaningful inference')\n",
        "st.text('4. A very significant difference in drivewheel category. Most high ranged cars seems')\n",
        "st.text('to prefer rwd drivewheel.')\n",
        "st.write('')\n",
        "st.write('')\n",
        "st.write('')\n",
        "\n",
        "\n",
        "st.header('Numerical Data')\n",
        "st.header('Car Length,Car Width,Car Height, Curb Weight')\n",
        "def scatter(x,fig):\n",
        "    plt.subplot(5,2,fig)\n",
        "    plt.scatter(cars[x],cars['price'])\n",
        "    plt.title(x+' vs Price')\n",
        "    plt.ylabel('Price')\n",
        "    plt.xlabel(x)\n",
        "\n",
        "fig9 = plt.figure(figsize=(10,20))\n",
        "\n",
        "scatter('carlength', 1)\n",
        "scatter('carwidth', 2)\n",
        "scatter('carheight', 3)\n",
        "scatter('curbweight', 4)\n",
        "\n",
        "plt.tight_layout()\n",
        "st.write(fig9)\n",
        "\n",
        "st.text('Inference :')\n",
        "\n",
        "st.text('1. Carwidth, carlength and curbweight seems to have a poitive correlation with price.')\n",
        "st.text('2. Carheight does not show any significant trend with price.')\n",
        "st.write('')\n",
        "st.write('')\n",
        "st.write('')\n",
        "\n",
        "st.header('Engine Size, Bore Ratio, Stroke, Compression Ratio, Horsepower, Peak rpm, Wheelbase, City mpg, Highway mpg')\n",
        "\n",
        "def pp(x,y,z):\n",
        "    sns.pairplot(cars, x_vars=[x,y,z], y_vars='price',size=4, aspect=1, kind='scatter')\n",
        "    # plt.show()\n",
        "    st.pyplot()\n",
        "\n",
        "pp('enginesize', 'boreratio', 'stroke')\n",
        "pp('compressionratio', 'horsepower', 'peakrpm')\n",
        "pp('wheelbase', 'citympg', 'highwaympg')\n",
        "\n",
        "\n",
        "st.text('Inference :')\n",
        "\n",
        "st.text('1. Enginesize, boreratio, horsepower, wheelbase - seem to have a significant')\n",
        "st.text('positive correlation with price.')\n",
        "st.text('2. Citympg, highwaympg - seem to have a significant negative correlation with price.')\n",
        "st.write('')\n",
        "st.write('')\n",
        "st.write('')\n",
        "\n",
        "np.corrcoef(cars['carlength'], cars['carwidth'])[0, 1]\n",
        "\n",
        "#Fuel economy\n",
        "cars['fueleconomy'] = (0.55 * cars['citympg']) + (0.45 * cars['highwaympg'])\n",
        "\n",
        "#Binning the Car Companies based on avg prices of each Company.\n",
        "cars['price'] = cars['price'].astype('int')\n",
        "temp = cars.copy()\n",
        "table = temp.groupby(['CompanyName'])['price'].mean()\n",
        "temp = temp.merge(table.reset_index(), how='left',on='CompanyName')\n",
        "bins = [0,10000,20000,40000]\n",
        "cars_bin=['Budget','Medium','Highend']\n",
        "cars['carsrange'] = pd.cut(temp['price_y'],bins,right=False,labels=cars_bin)\n",
        "\n",
        "fig10 = plt.figure(figsize=(10,4))\n",
        "st.header('Fuel Economy')\n",
        "plt.title('Fuel economy vs Price')\n",
        "sns.scatterplot(x=cars['fueleconomy'],y=cars['price'],hue=cars['drivewheel'])\n",
        "plt.xlabel('Fuel Economy')\n",
        "plt.ylabel('Price')\n",
        "\n",
        "plt.show()\n",
        "plt.tight_layout()\n",
        "st.write(fig10)\n",
        "\n",
        "st.text('Inference :')\n",
        "\n",
        "st.text('1. Fuel economy has an obvios negative correlation with price and is significant.')\n",
        "st.write('')\n",
        "st.write('')\n",
        "st.write('')\n",
        "\n",
        "\n",
        "st.header('Car Range')\n",
        "df = pd.DataFrame(cars.groupby(['fuelsystem','drivewheel','carsrange'])['price'].mean().unstack(fill_value=0))\n",
        "df.plot.bar(figsize=(10,4))\n",
        "plt.title('Car Range vs Average Price')\n",
        "plt.show()\n",
        "st.pyplot()\n",
        "\n",
        "st.text('Inference :')\n",
        "\n",
        "st.text('1. High ranged cars prefer rwd drivewheel with idi or mpfi fuelsystem.')"
      ]
    }
  ]
}